apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
      - name: binarycalculator
        image: northamerica-northeast2-docker.pkg.dev/project-f6aef8c8-2545-47ff-8f2/sofe3980u/binarycalculator:labfix9
        ports:
        - containerPort: 8080
